FROM supervisely/base-py-sdk:6.73.251

RUN export RELEASE_VERSION=6.73.296+promptable.segmentation.update
RUN pip3 install git+https://github.com/supervisely/supervisely.git@promptable-segmentation-update